# Basic and Advanced Indexing

Thus far we have seen that we can access the contents of a NumPy array by specifying an integer or slice-object as an index for each one of its dimensions. Indexing into and slicing along the dimensions of an array is known as basic indexing. NumPy also provides a sophisticated system of "advanced indexing", which permits us powerful means for accessing elements of an array that is flexible beyond specifying integers and slices along axes. For example, we can use advanced indexing to access all of the negative-valued elements from `x`.

```python
>>> import numpy as np
>>> x = np.array([[ -5,   2,  0, -7],
...               [ -1,   9,  3,  8],
...               [ -3,  -3,  4,  6]])

# Accessing the contents an array with "basic indexing".

# Access the column-1 of row-0 and row-2.
# This is an example of basic indexing. 
# A "view" of the underlying data in `x`
# is produced; no data is copied.
>>> x[::2, 1]
array([ 2, -3])

# An example of advanced indexing.
# Access all negative elements in `x`.
# This produces a copy of the accessed data.
>>> x[x < 0]
array([-5, -7, -1, -3, -3])
```

We will see that, where basic indexing provides us with a *view* of the data within the array, without making a copy of it, advanced indexing requires that a copy of the accessed data be made. This section is dedicated to understanding these two methods for the accessing data in a NumPy array.

## Basic Indexing
We begin this subsection by defining precisely what basic indexing is. Next, we will touch on each component of this definition, and lastly we will delve into the significance of basic indexing in the way it permits us to reference the underlying data of an array without copying it.

<div class="alert alert-info"> 

**Definition: Basic Indexing**: 

Given an $N$-dimensional array, `x`, `x[index]` invokes **basic indexing** whenever `index` is a *tuple* containing any combination of the following types of objects:

- integers
- [slice](http://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/SequenceTypes.html#Slicing) objects (e.g. `slice(0, 2)`)
- `Ellipsis` objects
- [numpy.newaxis](http://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html#Inserting-Size-1-Dimensions-into-An-Array) objects

Accessing the contents of an array via basic indexing *does not create a copy of those contents*. Rather, a "view" of the same underlying data is produced.
</div>


### Indexing with Integers and Slice Objects
Our discussion of [accessing data along multiple dimensions of a NumPy array](http://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/AccessingDataAlongMultipleDimensions.html) already provided a comprehensive rundown the use of integers and slices to access the contents of an array. According to the preceding definition, *these were all examples of basic indexing*.

To review the material discussed in that section, recall that one can access an individual element or a "subsection" of an $N$-dimensional array by specifying $N$ integers or slice-objects, or a combination of the two. We also saw that, when supplied fewer-than $N$ indices, NumPy will automatically "fill-in" the remaining indices with trailing slices. Keep in mind that the indices start at 0, such that the 4th column in `x` corresponds to column-3.

```python 
# Accessing the element located
# at row-1, last-column of `x`
>>> x[1, -1]
8

# Access the subarray of `x`
# contained within the first two rows
# and the first three columns
>>> x[:2, :3]
array([[-5,  2,  0],
       [-1,  9,  3]])

# NumPy fills in "trailing" slices
# if we don't supply as many indices
# as there are dimensions in that array
>>> x[0]  # equivalent to x[0, :]
array([-5,  2,  0, -7])
```

Recall that the familiar [slicing](http://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/SequenceTypes.html#Slicing) syntax actually forms `slice` objects "behind the scenes".

```python
# Reviewing the `slice` object

# equivalent: x[:2, :3]
>>> x[slice(None, 2), slice(None, 3)]
array([[-5,  2,  0],
       [-1,  9,  3]])
```

### Using a Tuple as a N-dimensional Index
According to its definition, we must supply our array-indices as a tuple in order to invoke basic indexing. As it turns out, we have been forming tuples of indices all along! That is, every time that we index into a an array using the syntax `x[i, j, k]`, we are actually forming a [tuple](http://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/SequenceTypes.html#Tuples) containing those indices. I.e. `x[i, j, k]` is equivalent to `x[(i, j, k)]`.

`x[i, j, k]` forms the tuple `(i, j, k)` and passes that to the array's "get-item" mechanism. Thus, `x[0, 3]` is equivalent to `x[(0, 3)]`. 


```python
# N-dimensional indexing utilizes tuples:
# `x[i, j, k]` is equivalent to `x[(i, j, k)]`

# equivalent: x[1, -1]
>>> x[(1, -1)]  
8

# equivalent: x[:2, :3]
>>> x[(slice(None, 2), slice(None, 3))]  
array([[-5,  2,  0],
       [-1,  9,  3]])

# equivalent: x[0]
>>> x[(0,)]
array([-5,  2,  0, -7])
```

All objects used in this "get-item" syntax are packed into a tuple. For instance, `x[0, (0, 1)]` is equivalent to `x[(0, (0, 1))]`. You may be surprised to find that this is a valid index. However, see that *it does not invoke basic indexing*; the index used here is a tuple that contains an integer *and another tuple*, which is not permitted by the rules of basic indexing.

Finally, note that the rules of basic indexing specifically call for a *tuple* of indices. Supplying a list of indices triggers advanced indexing rather than basic indexing!

```python
# basic indexing specifically requires a tuple
>>> x[(1, -1)]  
8

# indexing with a list triggers advanced indexing
>>> x[[1, -1]]
array([[-1,  9,  3,  8],
       [-3, -3,  4,  6]])
```

### Ellipsis and Newaxis objects
Recall from our discussion of broadcasting, that the `numpy.newaxis` object can be passed as an index to an array, in order to [insert a size-1 dimension into the array](http://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html#Inserting-Size-1-Dimensions-into-An-Array).

```python
# inserting size-1 dimensions with `np.newaxis`
>>> x.shape
(3, 4)

>>> x[np.newaxis, :, :, np.newaxis].shape
(1, 3, 4, 1)

# forming the index as an explicit tuple
>>> x[(np.newaxis, slice(None), slice(None), np.newaxis)].shape
(1, 3, 4, 1)
```

We can also use the built-in `Ellipsis` object in order to insert slices into our index such that the index has as many entries as the array has dimensions. In the same way that `:` can be used to represent a `slice` object, `...` can be used to represent an `Ellipsis` object.

```python
>>> y = np.array([[[ 0,  1,  2,  3],
...                [ 4,  5,  6,  7]],
...        
...               [[ 8,  9, 10, 11],
...                [12, 13, 14, 15]],
...        
...               [[16, 17, 18, 19],
...                [20, 21, 22, 23]]])

# equivalent: `y[:, :, 0]`
>>> y[..., 0]
array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

# using an explicit tuple
>>> y[(Ellipsis, 0)]
array([[ 0,  4],
       [ 8, 12],
       [16, 20]])

# equivalent: `y[0, :, 1]`
>>> y[0, ..., 1]
array([1, 5])
```

An index cannot possess more than one `Ellipsis` entry. This can be extremely useful when working with arrays of varying dimensionalities. To access column-0 along all dimensions of an array, `z`, would look like `z[:, 0]` for a 2D array, `z[:, :, 0]` for a 3D array, and so on. `z[..., 0]` succinctly encapsulates all iterations of this. 

<div class="alert alert-warning"> 


**Reading Comprehension: Basic Indexing**

Given a shape-(4, 3) array,

```python
>>> arr = np.array([[ 0,  1,  2,  3],
...                 [ 4,  5,  6,  7],
...                 [ 8,  9, 10, 11]])
```

which of the following indexing schemes perform basic indexing. That is, in which instances does the index satisfy the rules of basic indexing?

 - `arr[0]`
 - `arr[:-1, 0]`
 - `arr[(2, 3)]`
 - `arr[[2, 0]]`
 - `arr[np.array([2, 0])]`
 - `arr[(0, 1), (2, 3)]`
 - `arr[slice(None), ...]`
 - `arr[(np.newaxis, 0, slice(1, 2), np.newaxis)]`

</div>

## Views of an Array and Augmented Assignments

### Producing a View of an Array
As stated above, using basic indexing does not return a copy of the data being accessed, rather it produces a *view* of the underlying data. NumPy provides the function `numpy.shares_memory` to determine if two arrays refer to the same underlying data.

```python
>>> z = np.array([[ 3.31,  4.71,  0.4 ],
...               [ 0.21,  2.85,  3.21],
...               [-3.77,  4.53, -1.15]])

# `subarray` is column-0 of `z`, via
# basic indexing
>>> subarray = z[:, 0]
>>> subarray
array([ 3.31,  0.21, -3.77])

# `subarray` is a view of the array data 
# referenced by `z`
>>> np.shares_memory(subarray, z)
True
```

The function `numpy.copy` can be used to create a copy of an array, such that it no longer shares memory with any other array.

```python
# creating a distinct copy of an array
>> new_subarray = np.copy(subarray)
>>> new_subarray
array([ 3.31,  0.21, -3.77])

>>> np.shares_memory(new_subarray, z)
False
```

Utilizing an array in a mathematical expression returns an entirely distinct array, that does not share memory with the original array.

```python
# mathematical expressions like `subarray + 2`
# produce distinct arrays, not views
>>> np.shares_memory(subarray + 2, subarray)
False
```

NumPy does provide mechanisms for performing mathematical operations to directly update the underlying data of an array, via [augmented assignment statements](http://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Basic_Objects.html#Augmented-Assignment-Statements), which we will now discuss.

### Updating an Array with Augmented Assignments
Whereas mathematical expressions involving NumPy arrays produce distinct arrays, [augmented assignment expressions](http://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Basic_Objects.html#Augmented-Assignment-Statements) can be used to directly update the underlying data referenced by that array, and any other views of that data. We will demonstrate this distinction here.

```python
>>> a = np.array([[ 0,  1,  2,  3],
...               [ 4,  5,  6,  7],
...               [ 8,  9, 10, 11]])

>>> b = a[0]
>>> c = a[0]

# `b` and `c` are both views of row-0 of `a`
>>> np.shares_memory(a, b) and np.shares_memory(a, c)
True

# updating `b` using a mathematical expression creates
# a distinct array, which is divorced from `a` and `c`
>>> b = b * -1
>>> b
array([ 0, -1, -2, -3])

>>> np.shares_memory(a, b)
False

# updating `c` using augmented assignment updates the 
# underlying data that `c` is a view of
>>> c *= -2
>>> c
array([ 0, -2, -4, -6])

# note that this update is reflected in `a` as well,
# as it still shares memory with `c`
>>> a
array([[ 0, -2, -4, -6],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

>>> np.shares_memory(a, c)
True
```

You can directly update a subsection of an array via assignment.

```python
# Assign row-0, column-0 with the value -40
# and row-0, column-2 with the value -50
>>> a[0, ::2] = (-40, -50)
>>> a
array([[-40,  -2, -50,  -6],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])
```
Again, this updates the underlying data, and thus all views of this data reflect this change.
```python
# `c` is still a view of row-0 of `a`
>>> c
array([-40,  -2, -50,  -6])
```

It is critical to understand the relationship between arrays and the underlying data that they reference. Augmented assignments provide a powerful means for updating data in-place, without needing to create a new copy of the data. Thus an expression like `array += 3` *is computationally more efficient than its explicit counterpart*, `array = array + 3`.  That being said, to *unwittingly* affect multiple arrays via augmented assignment, is a big mistake; this produces hard-to-find bugs in the code of novice NumPy users.   

<div class="alert alert-info"> 

**Definition: Basic Indexing**: 

Given an $N$-dimensional array, `x`, `x[index]` invokes **basic indexing** whenever `index` is a *tuple* containing any combination of the following types of objects:

- integers
- [slice](http://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/SequenceTypes.html#Slicing) objects (e.g. `slice(0, 2)`)
- `Ellipsis` objects
- [numpy.newaxis](http://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html#Inserting-Size-1-Dimensions-into-An-Array) objects

Accessing the contents of an array via basic indexing *does not create a copy of those contents*. Rather, a "view" of the same underlying data is produced.
</div>

## Reading Comprehension Solutions

**Basic Indexing: Solution**

In which instances does the index used satisfy the rules of basic indexing?

 - `arr[0]` ✔
 - `arr[:-1, 0]`  ✔
 - `arr[(2, 3)]`  ✔
 - `arr[[2, 0]]`  ✘ (index is a `list`, not a `tuple`)
 - `arr[np.array([2, 0])]` ✘ (index is a `numpy.ndarray`, not a `tuple`)
 - `arr[:, (2, 3)]`  ✘ (index contains a tuple; only `int`, `slice`, `np.newaxis`, `Ellipsis` allowed)
 - `arr[slice(None), ...]`  ✔
 - `arr[(np.newaxis, 0, slice(1, 2), np.newaxis)]`  ✔