# Basic and Advanced Indexing

Thus far we have seen that we can access the contents of a NumPy array by specifying an integer or slice-object as an index for each one of its dimensions. 

```python
# accessing the contents an array with "basic indexing"
>>> import numpy as np
x = np.array([[ -5,   2,  0, -7],
              [ -1,   9,  3,  8],
              [ -3,  -3,  4,  6]])

# access the column-1 of row-0 and row-2
>>> x[::2, 1]
array([ 2, -3])
```

However, NumPy also provides a sophisticated system of "advanced indexing", which permits us powerful means for accessing elements of an array that is flexible beyond specifying integers and slices and indices. For example, we can access all of the negative-valued elements from `x`:

```python
# An example of advanced indexing.
# Access all negative elements in `x`
>>> x[x < 0]
array([-5, -7, -1, -3, -3])
```

This section is dedicated to understanding the capabilities of advanced indexing and its difference from basic indexing. First, we will 

## Basic Indexing

### Review
Our discussion of [accessing data along multiple dimensions of a NumPy array](http://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/AccessingDataAlongMultipleDimensions.html) already provided a nearly-comprehensive overview of basic indexing. To review the material discussed in that section, recall that one can access an individual element or a "subsection" of an $N$-dimensional array by specifying $N$ integers or slice-objects, or a combination of the two. We also saw that, when supplied fewer-than $N$ indices, NumPy will automatically "fill-in" the remaining indices with trailing slices. Keep in mind that the indices start at 0, such that the 4th column in `x` corresponds to column-3.

```python 
# Reviewing basic indexing.

# Accessing the element located
# at row-1, last-column of `x`
>>> x[1, -1]
8

# Access the subsection of `x`
# contained within the first two rows
# and the first three columns
>>> x[:2, :3]
array([[-5,  2,  0],
       [-1,  9,  3]])

# NumPy fills in "trailing" slices
# if we don't supply as many indices
# as there are dimensions in that array
>>> x[0]  # equivalent to x[0, :]
array([-5,  2,  0, -7])
```

### N-dimensional Indices Are Tuples
To understand 